FROM node:16-alpine as builder
# Copy the package.json and install dependencies
COPY package*.json ./
RUN npm install
# Copy rest of the files
COPY . .
# Build the project
RUN npm run build
CMD ["/bin/bash", "-c", "node server.cjs"]
